version: '3.8'

services:
#  запуск api
  app_api:
    build: .
#    command: uvicorn app.main:app --host 0.0.0.0
    command: bash -c 'while !</dev/tcp/app_db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=qwerty
      - DB_DATABASE=grka_test_db
      - DB_HOST=app_db
      - DB_PORT=5432
    depends_on:
      - app_db
    restart: always

  app_db:
      image: postgres:15.2
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: grka_test_db
        TZ: "Europe/Minsk"
        PTZ: "Europe/Minsk"
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data:cached

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  postgres_data: