"""'udate_relasion_ship_organization'

Revision ID: 54ea9a2a2ff9
Revises: 3dda85baa05c
Create Date: 2022-12-21 17:09:42.577683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54ea9a2a2ff9'
down_revision = '3dda85baa05c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_access_tor_id', table_name='user_access_tor')
    op.drop_column('user_access_tor', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access_tor', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_index('ix_user_access_tor_id', 'user_access_tor', ['id'], unique=False)
    # ### end Alembic commands ###
