"""'update_subunit_add_title'

Revision ID: 6fdb89eec3e5
Revises: 4fbce2e9f71a
Create Date: 2023-02-15 12:07:43.505729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fdb89eec3e5'
down_revision = '4fbce2e9f71a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('subunit', sa.Column('title', sa.String(length=160), nullable=False))
    # op.drop_index('ix_subunit_fullname', table_name='subunit')
    # op.create_index(op.f('ix_subunit_title'), 'subunit', ['title'], unique=False)
    # op.drop_column('subunit', 'fullname')
    op.alter_column('subunit', column_name='fullname', new_column_name='title', existing_type=sa.String(length=160))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('subunit', sa.Column('fullname', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_subunit_title'), table_name='subunit')
    # op.create_index('ix_subunit_fullname', 'subunit', ['fullname'], unique=False)
    # op.drop_column('subunit', 'title')
    op.alter_column('subunit', column_name='title', new_column_name='name', existing_type=sa.VARCHAR(length=60))
    # ### end Alembic commands ###
