"""'update_table_bookingTransport'

Revision ID: d099100ed55c
Revises: c886e6e0a491
Create Date: 2023-02-16 14:43:50.480941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd099100ed55c'
down_revision = 'c886e6e0a491'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookingtransport', sa.Column('count_man', sa.Integer(), nullable=True))
    op.add_column('bookingtransport', sa.Column('description', sa.String(length=300), nullable=True))
    op.add_column('bookingtransport', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookingtransport', 'organization', ['organization_id'], ['id'])
    op.drop_column('bookingtransport', 'details')
    op.add_column('transport', sa.Column('description', sa.String(length=200), nullable=True))
    op.drop_column('transport', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('details', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('transport', 'description')
    op.add_column('bookingtransport', sa.Column('details', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookingtransport', type_='foreignkey')
    op.drop_column('bookingtransport', 'organization_id')
    op.drop_column('bookingtransport', 'description')
    op.drop_column('bookingtransport', 'count_man')
    # ### end Alembic commands ###
