"""'added_table_transport'

Revision ID: c886e6e0a491
Revises: cc6394cee031
Create Date: 2023-02-15 17:25:37.426587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c886e6e0a491'
down_revision = 'cc6394cee031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('details', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookingtransport', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('bookingtransport', sa.Column('transport_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'bookingtransport', 'transport', ['transport_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookingtransport', type_='foreignkey')
    op.drop_column('bookingtransport', 'transport_id')
    op.drop_column('bookingtransport', 'is_active')
    op.drop_table('transport')
    # ### end Alembic commands ###
