"""'added_active_item'

Revision ID: 4fbce2e9f71a
Revises: 54ea9a2a2ff9
Create Date: 2023-02-13 13:51:54.816855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbce2e9f71a'
down_revision = '54ea9a2a2ff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'is_active')
    # ### end Alembic commands ###
