"""'update_subunit_organization'

Revision ID: cc6394cee031
Revises: 62f3b8d43850
Create Date: 2023-02-15 14:34:47.995674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6394cee031'
down_revision = '62f3b8d43850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_name', table_name='organization')
    op.create_index(op.f('ix_organization_title'), 'organization', ['title'], unique=False)
    op.drop_index('ix_subunit_fullname', table_name='subunit')
    op.create_index(op.f('ix_subunit_title'), 'subunit', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subunit_title'), table_name='subunit')
    op.create_index('ix_subunit_fullname', 'subunit', ['title'], unique=False)
    op.drop_index(op.f('ix_organization_title'), table_name='organization')
    op.create_index('ix_organization_name', 'organization', ['title'], unique=False)
    # ### end Alembic commands ###
