"""'change_organization_column_title'

Revision ID: 62f3b8d43850
Revises: 6fdb89eec3e5
Create Date: 2023-02-15 14:08:47.940520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f3b8d43850'
down_revision = '6fdb89eec3e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('organization', sa.Column('title', sa.String(length=100), nullable=False))
    # op.drop_index('ix_organization_name', table_name='organization')
    # op.create_index(op.f('ix_organization_title'), 'organization', ['title'], unique=False)
    # op.drop_column('organization', 'name')
    # op.drop_index('ix_subunit_fullname', table_name='subunit')
    # op.create_index(op.f('ix_subunit_title'), 'subunit', ['title'], unique=False)
    op.alter_column('organization', column_name='name', new_column_name='title',)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_subunit_title'), table_name='subunit')
    # op.create_index('ix_subunit_fullname', 'subunit', ['title'], unique=False)
    # op.add_column('organization', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # op.drop_index(op.f('ix_organization_title'), table_name='organization')
    # op.create_index('ix_organization_name', 'organization', ['name'], unique=False)
    # op.drop_column('organization', 'title')
    op.alter_column('organization', column_name='name', new_column_name='title')
    # ### end Alembic commands ###
