"""Update_bookingTransport_added_column_duration

Revision ID: 1233de0047c4
Revises: d099100ed55c
Create Date: 2023-02-23 13:54:46.742519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1233de0047c4'
down_revision = 'd099100ed55c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookingtransport', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookingtransport', 'duration')
    # ### end Alembic commands ###
