"""'2022_12_07_added_organizatonId_in_subunit'

Revision ID: cc8885643172
Revises: 65a7d37cd745
Create Date: 2022-12-13 17:08:26.572266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8885643172'
down_revision = '65a7d37cd745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subunit', sa.Column('fullname', sa.String(length=60), nullable=False))
    op.add_column('subunit', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subunit_fullname'), 'subunit', ['fullname'], unique=False)
    op.create_foreign_key(None, 'subunit', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subunit', type_='foreignkey')
    op.drop_index(op.f('ix_subunit_fullname'), table_name='subunit')
    op.drop_column('subunit', 'organization_id')
    op.drop_column('subunit', 'fullname')
    # ### end Alembic commands ###
